"""drop transcript_url

Revision ID: 67ac98ee4166
Revises: f637d4cd5c8d
Create Date: 2026-08-09 17:12:19.711536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ac98ee4166'
down_revision: Union[str, Sequence[str], None] = 'f637d4cd5c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'transcript_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('transcript_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
