"""add episode image_url

Revision ID: 739a4ca980cb
Revises: 67ac98ee4166
Create Date: 2026-08-26 09:09:40.068415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739a4ca980cb'
down_revision: Union[str, Sequence[str], None] = '67ac98ee4166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'image_url')
    # ### end Alembic commands ###
