"""add confidence to episode_speakers

Revision ID: 8cc06631f220
Revises: 6fd15e2631eb
Create Date: 2026-05-29 17:57:04.866785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc06631f220'
down_revision: Union[str, Sequence[str], None] = '6fd15e2631eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode_speakers', sa.Column('confidence', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode_speakers', 'confidence')
    # ### end Alembic commands ###
