"""add chunks episode_id and parent_id indexes

Revision ID: a66500b37563
Revises: 8cc06631f220
Create Date: 2026-06-02 19:59:39.278500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66500b37563'
down_revision: Union[str, Sequence[str], None] = '8cc06631f220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_index("chunks_embedding_idx", table_name="chunks")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('chunks_episode_id_idx', 'chunks', ['episode_id'], unique=False)
    op.create_index('chunks_parent_id_idx', 'chunks', ['parent_id'], unique=False)
    # ### end Alembic commands ###
    op.create_index(
        "chunks_embedding_idx_leaf",
        "chunks",
        ["embedding"],
        postgresql_using="ivfflat",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_where="chunk_level = 'leaf'",
    )


def downgrade() -> None:
    op.drop_index('chunks_parent_id_idx', table_name='chunks')
    op.drop_index('chunks_episode_id_idx', table_name='chunks')
    op.drop_index("chunks_embedding_idx_leaf", table_name="chunks")
    op.create_index(
        "chunks_embedding_idx",
        "chunks",
        ["embedding"],
        postgresql_using="ivfflat",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )

